// All user-facing English strings. Add sibling files (sn.js, nd.js) with the same keys for Shona / Ndebele.
export default {
  appName: 'Rest Assured',

  nav: {
    label: 'Main',
    home: 'Battery',
    log: 'Log',
    recent: 'Recent',
    team: 'Team',
    settings: 'Settings',
  },

  setup: {
    heading: 'Choose a passphrase',
    intro: 'Your passphrase encrypts everything this app keeps on this phone. Nothing is sent anywhere.',
    warning: 'If you forget it, your data cannot be recovered — by design. There are no hints and no reset.',
    passphrase: 'Passphrase',
    passphraseHint: 'At least 8 characters. A few unrelated words work well.',
    confirm: 'Enter it again',
    submit: 'Create passphrase',
    busy: 'Setting up…',
    tooShort: 'Use at least 8 characters.',
    mismatch: 'The two passphrases do not match.',
  },

  unlock: {
    heading: 'Unlock',
    passphrase: 'Passphrase',
    submit: 'Unlock',
    busy: 'Unlocking…',
    wrong: 'That passphrase did not work. Try again.',
    empty: 'Enter your passphrase.',
  },

  home: {
    heading: 'Your battery',
    estimate: 'An estimate from what you logged in the last 14 days — not a medical measurement.',
    gaugeLabel: (level, band) => `Battery ${level}%, ${band}`,
    bands: {
      high: 'Well rested',
      mid: 'Steady',
      low: 'Running low',
      veryLow: 'Very low',
    },
    empty: 'Nothing logged yet. Log an activity to see an estimate.',
    logCta: 'Log an activity',
    coverHeading: 'Time to recharge',
    cover: 'Your battery is low. Consider asking a teammate to hold your role.',
    coverNote: 'Rest is part of the work, not a failure. Only you can see this.',
    loadError: 'Could not load your entries.',
  },

  log: {
    heading: 'Log an activity',
    intro: 'Only the day, day part and kind of activity are kept. No notes, no places, no names.',
    date: 'Date',
    dayPart: 'Part of the day',
    type: 'Activity',
    duration: 'How long',
    intensity: 'How demanding',
    selfCheck: 'How do you feel? (optional)',
    selfCheckSkip: 'Skip',
    submit: 'Save',
    busy: 'Saving…',
    saved: 'Saved.',
    genericError: 'Could not save this entry.',
    typeRequired: 'Choose an activity.',
  },

  recent: {
    heading: 'Last 14 days',
    note: 'Entries older than 14 days are deleted automatically.',
    empty: 'No entries in the last 14 days.',
    selfCheck: (n) => `Feeling ${n}/5`,
    loadError: 'Could not load your entries.',
  },

  settings: {
    heading: 'Settings',
    lockHeading: 'Lock',
    lockNote: 'The app also locks itself after 2 minutes in the background.',
    lock: 'Lock now',
    locked: 'Locked.',
    demoHeading: 'Demo data',
    demoNote: 'Adds 14 days of made-up entries so you can try the app.',
    demo: 'Load demo data',
    demoBusy: 'Loading…',
    demoDone: (n) => `Added ${n} demo entries.`,
    demoError: 'Could not load demo data.',
    wipeHeading: 'Panic wipe',
    wipeNote: 'Deletes your passphrase and every entry on this phone immediately.',
    wipe: 'Panic wipe',
    wipeConfirmText: 'Delete everything now? This cannot be undone.',
    wipeConfirm: 'Yes, delete everything',
    wipeCancel: 'Cancel',
    wipeBusy: 'Deleting…',
    wiped: 'Everything was deleted.',
    wipeError: 'Could not delete. Try again.',
  },

  team: {
    heading: 'Team',
    back: 'Back',
    done: 'Done',
    genericError: 'Something went wrong. Try again.',
    loadError: 'Could not load your team.',
    preparing: 'Preparing…',

    none: {
      intro: 'A team starts with a covenant: a few shared words about how you look after each other, including rest.',
      start: 'Start a team',
      join: 'Join a team',
    },

    start: {
      heading: 'Start a team',
      intro: 'Write your covenant together. Rest is part of the work — say how you will make room for it.',
      neutral: 'Keep it neutral — no names of people, places or groups.',
      name: 'Team name (optional)',
      nameHint: 'Up to 30 characters. Something only you would recognise.',
      purpose: 'Our purpose',
      purposeHint: 'Up to 200 characters. Why do we do this together?',
      purposePlaceholder: 'We look after each other so we can keep going for the long haul.',
      commitments: 'Our commitments',
      commitmentsHint: 'Up to 5, each up to 80 characters.',
      commitment: (n) => `Commitment ${n}`,
      commitmentPlaceholders: [
        'We rest without apologising.',
        'We ask for cover early, not at breaking point.',
        'We check in on each other, not up on each other.',
        'We share the load when someone is running low.',
        'We honour time off.',
      ],
      addCommitment: 'Add a commitment',
      removeCommitment: (n) => `Remove commitment ${n}`,
      pseudonym: 'Your pseudonym',
      pseudonymHint: 'Up to 20 characters. Not your real name.',
      purposeRequired: 'Write a purpose for your team.',
      pseudonymRequired: 'Choose a pseudonym.',
      submit: 'Create team',
      busy: 'Creating…',
      created: 'Team created.',
    },

    join: {
      heading: 'Join a team',
      scanStep: 'Scan the invite QR from the person inviting you, or paste the invite code.',
      notInvite: 'That is not an invite code.',
      codeStep: 'Type the join code they read aloud.',
      code: 'Join code',
      codeHint: 'Letters and numbers, like 7KQ2-M9XD-4T.',
      badCode: 'That join code does not look right. Check it and try again.',
      wrongCode: 'Wrong join code, or not an invite. Check the code and try again.',
      open: 'Open invite',
      opening: 'Opening…',
      covenantStep: 'Read the covenant together before you join.',
      agree: 'We agree',
      mustAgree: 'Tick "We agree" to join.',
      submit: 'Join team',
      busy: 'Joining…',
      joined: 'You joined the team.',
    },

    home: {
      unnamed: 'Your team',
      covenant: 'Our covenant',
      summaryHeading: 'Latest check-in',
      noSummary: 'No recent check-in. Run one together to see how the team is doing.',
      lowCount: (low, total) => `${low} of ${total} of us are running low`,
      hiddenCount: 'Fewer than 3 people checked in, so the team total stays hidden.',
      asOf: (date, expires) => `As of ${date} · clears after ${expires}`,
      lowNote: 'Running low is a signal to share the load, not a failure.',
      statusesHeading: 'Shared by choice',
      bands: { ok: 'Okay', low: 'Running low' },
      shareLabel: 'Share my status (okay / running low) at check-ins',
      shareNote:
        'When on, your pseudonym and "okay" or "running low" appear in the team summary. When off, you are only counted in the total. Your battery level and activities are never shared.',
      shareOn: 'Your status will be shared at the next check-in.',
      shareOff: 'Your status will not be shared.',
      actions: 'Check-in',
      myStatus: 'My status QR',
      runCheckin: 'Run check-in',
      scanSummary: 'Scan summary',
      invite: 'Invite someone',
      leaveHeading: 'Leave team',
      leaveNote: 'Deletes this team and its covenant from this phone.',
      leave: 'Leave team',
      leaveConfirmText: 'Leave this team? You will need a new invite to rejoin.',
      leaveConfirm: 'Yes, leave',
      leaveCancel: 'Cancel',
      left: 'You left the team.',
    },

    status: {
      heading: 'My status',
      intro: 'Show this to the person running the check-in.',
      contains: 'This code says only that you checked in today and whether you are running low.',
      containsShared: (pseudonym) => `Because sharing is on, it also shows "${pseudonym}" with okay or running low.`,
      never: 'It never contains your battery level or activities.',
      busy: 'Preparing…',
    },

    checkin: {
      heading: 'Run check-in',
      intro: 'Scan each person’s "My status" QR, then tap Finish. Your own status is added automatically.',
      count: (n) => (n === 1 ? '1 person scanned (plus you)' : `${n} people scanned (plus you)`),
      added: 'Added.',
      duplicate: 'Already scanned.',
      notStatus: 'That is not a status code from this team.',
      finish: 'Finish',
      busy: 'Finishing…',
      cancel: 'Cancel',
      summaryHeading: 'Check-in summary',
      summaryIntro: 'Everyone scans this with "Scan summary". The individual codes you scanned have been discarded.',
    },

    scanSummary: {
      heading: 'Scan summary',
      intro: 'Scan the summary QR from the person who ran the check-in, or paste the code.',
      notSummary: 'That is not a summary code from this team.',
      updated: 'Team summary updated.',
    },

    invite: {
      heading: 'Invite someone',
      intro: 'Do this in person. Read the code aloud; the QR alone is not enough to join.',
      codeLabel: 'Join code',
      busy: 'Preparing invite…',
      newCode: 'New code',
    },

    scanner: {
      startCamera: 'Scan with camera',
      stopCamera: 'Stop camera',
      cameraError: 'Could not use the camera. Paste the code instead.',
      video: 'Camera view',
      paste: 'Or paste a code',
      use: 'Use code',
      empty: 'Paste a code first.',
    },

    code: {
      show: 'Show code as text',
      label: 'Code',
      copy: 'Copy code',
      copied: 'Copied.',
      copyFailed: 'Could not copy. Select the text and copy it.',
      qr: 'QR code',
    },
  },

  dayParts: {
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    night: 'Night',
  },

  types: {
    action: 'Action',
    meeting: 'Meeting',
    travel: 'Travel',
    support: 'Support',
    admin: 'Admin',
    rest: 'Rest',
    sleep: 'Sleep',
  },

  intensity: {
    1: 'Light',
    2: 'Moderate',
    3: 'Heavy',
  },

  selfCheck: {
    1: '1 · Fresh',
    2: '2',
    3: '3',
    4: '4',
    5: '5 · Drained',
  },

  duration: (min) => {
    const h = Math.floor(min / 60);
    const m = min % 60;
    if (!h) return `${m} min`;
    return m ? `${h} h ${m} min` : `${h} h`;
  },

  autoLocked: 'Locked after time in the background.',
};
